# Generated by Django 3.2.3 on 2021-07-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default=300, max_length=300),
            preserve_default=False,
        ),
    ]
